
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    password: test
    username: test
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: false
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
  sql:
    init:
      platform: postgres
